daftarKata = [
    "anak", "apel", "ayah", "baju", "bola", "bulan", "cinta", "daging", "dalam", "darah",
    "dunia", "gelap", "gula", "guru", "hati", "ibu", "ilmu", "jalan", "jam", "jarak",
    "jari", "kaki", "kamar", "kata", "kawan", "kecil", "keluar", "kertas", "kunci", "lampu",
    "lebih", "makan", "mata", "mulut", "musik", "nama", "nyanyi", "oleh", "orang", "pakaian",
    "pantai", "pohon", "rumah", "sakit", "sandal", "sayang", "sejuk", "senang", "sinar",
    "suara", "tangan", "tanah", "tari", "telur", "teman", "terang", "udara", "waktu", "warna",
    "yakin", "yayasan", "yudisium", "zaman", "zebra", "abu", "akal", "alas", "alat", "aliran",
    "ambulans", "amplop", "angin", "angka", "antara", "apel", "asap", "asam", "asap", "aurora",
    "bacok", "badai", "bagian", "bahagia", "bahasa", "bahan", "baju", "bakar", "balap", "bali",
    "balon", "bantal", "bandara", "banding", "bangku", "bantal", "banjir", "barang", "baru",
    "batang", "batas", "batu", "bawa", "belajar", "belanja", "belok", "bendera", "benih", "beri",
    "berita", "bersih", "bertemu", "besar", "biaya", "bijak", "biji", "bintang", "bisik", "biskuit",
    "bulan", "bumi", "bunga", "bunuh", "burung", "cabai", "cabe", "cakar", "cepat", "cerah",
    "cerita", "cinta", "cuci", "curi", "daging", "dalam", "darah", "datang", "daya", "degan",
    "dengar", "desa", "depan", "deras", "dewa", "dia", "diri", "dosa", "dua", "duit", "emas",
    "endap", "enggan", "gairah", "galau", "ganda", "gandum", "garis", "gatal", "gemuk", "genting",
    "gila", "goreng", "gudang", "hantu", "harap", "hati", "hebat", "hidup", "hijau", "hujan",
    "ikut", "indah", "ingat", "ingin", "istana", "itu", "jadi", "jaga", "jahat", "jakarta",
    "jalur", "jantung", "jari", "jas", "jauh", "jendela", "jeruk", "jomblo", "juga", "jurus",
    "kabur", "kaca", "kado", "kaki", "kalau", "kaleng", "kamar", "kambing", "kamu", "kangen",
    "kantong", "kapal", "kapan", "karet", "karya", "kasih", "katanya", "kaya", "kayu", "kebun",
    "kecil", "kecup", "kedua", "kejam", "keluarga", "kencan", "kenyang", "kerja", "kesal", "ketua",
    "khusus", "kiamat", "kiat", "kira", "kiri", "kita", "kopi", "kotor", "kucing", "kuda",
    "kunci", "kupu-kupu", "kurus", "kutu", "laba", "laku", "lama", "lambat", "lampu", "lari",
    "latih", "lawan", "lebat", "ledak", "leher", "lelah", "lemah", "lembut", "lepas", "lihat",
    "lintas", "listrik", "lobi", "longgar", "luka", "lupa", "lurah", "madu", "maju", "makam",
    "makan", "makna", "malam", "manis", "masak", "mata", "mayat", "maya", "media", "medis",
    "melati", "mentah", "mesin", "mimpi", "minum", "mobil", "moda", "muka", "musuh", "naik",
    "nasihat", "nasi", "nafas", "nahkoda", "nama", "nasi", "navigasi", "nikmat", "nol", "nyala",
    "nyaman", "obat", "olahraga", "orang", "pakaian", "paku", "paman", "pantai", "parah", "pasar",
    "pasir", "patah", "payung", "pelangi", "pelayan", "pelita", "pena", "penari", "penasaran", "pendek",
    "penulis", "perahu", "pergi", "pesawat", "petani", "pijat", "pikir", "pilih", "pinggir", "pipi",
    "piramida", "pohon", "polisi", "pulau", "punggung", "putar", "putih", "raja", "rumah", "sakit",
    "salju", "sandal", "sapi", "sayang", "sebelah", "sejuk", "sakit", "senyum", "sial", "sia-sia",
    "siang", "sifat", "singa", "sini", "siswa", "suka", "suara", "tabir", "tahan", "takut",
    "tanda", "tari", "tarik", "tas", "tebak", "tegas", "tema", "tembok", "tembaga", "teman",
    "tenang", "terang", "teras", "teriak", "tidur", "tiga", "tikus", "tinggi", "tinta", "toko",
    "tongkat", "topi", "truk", "tua", "tubuh", "tugu", "tulis", "tumpah", "tusuk", "tujuh",
    "udara", "uang", "ubur-ubur", "ular", "unggun", "unik", "usaha", "utama", "virus", "waktu",
    "warna", "waspada", "waktu", "wajah", "warga", "warta", "xenon", "yang", "yudisium",
    "yuk", "zaman", "zat", "zebra", "zodiak"
]